### PR TITLE
Gitignore: add Xcode intermediate file types.

### PR DESCRIPTION
**Pull request by gershonho**

### CODE REVIEW

**Comment by StatusReport** [comment]
There are multiple changes here:
- Added files.
- Modifies files.
- Xcode project.

Let's split those to different PRs.

**Comment by gershonho** [comment]
Done. 
This first PR adds auto-generated header files to the repository (to eliminate the auto-generation step).

**Comment by StatusReport** [comment]
Can't this be done automatically by an additional Xcode build step?

**Comment by gershonho** [comment]
Done.

**Comment by gershonho** [comment]
Currently this PR contains only .gitignore changes. Once it is merged - I will create the next PR with more changes/additions.

**Pull request merged**
